# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.25'

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Staticcheck is a go vet on steroids
    - unused        # Check for unused code

    # Additional recommended linters
    - gofmt         # Gofmt checks whether code was gofmt-ed
    - goimports     # Check import statements
    - revive        # Fast, configurable, extensible, flexible linter
    - misspell      # Finds commonly misspelled English words
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - nakedret      # Finds naked returns in functions
    - prealloc      # Finds slice declarations that could be preallocated
    - exportloopref # Checks for pointers to enclosing loop variables
    - noctx         # Finds sending http request without context.Context
    - gosec         # Security problems
    - bodyclose     # Checks HTTP body is closed
    - nilerr        # Finds code that returns nil even if it checks that the error is not nil
    - errorlint     # Find code that will cause problems with error wrapping
    - gocritic      # Extensible Go source code linter
    - gocyclo       # Cyclomatic complexity
    - dupl          # Code clone detection
    - goconst       # Repeated strings that could be constants
    - godot         # Check if comments end with a period
    - whitespace    # Tool for detection of leading/trailing whitespace

  disable:
    - exhaustive    # Too strict for this project
    - exhaustruct   # Too strict for this project
    - varnamelen    # Variable name length

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow      # Can be too strict

  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120
    tab-width: 4

  unused:
    check-exported: false

  unparam:
    check-exported: false

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - paramTypeCombine  # Can be noisy

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked (handled by errcheck)

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude protobuf generated files
    - path: \.pb\.go$
      linters:
        - gofmt
        - goimports
        - revive
        - govet
        - staticcheck
        - unused

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  fix: false

severity:
  default-severity: error
  case-sensitive: false
