---
# yamllint configuration
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Comments
  comments:
    min-spaces-from-content: 1

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

  # Document start
  document-start:
    present: false

  # Empty values
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true

ignore: |
  .git/
  vendor/
  node_modules/
