version: '3.8'

services:
  github-runner-debian:
    build:
      context: github-runner-debian
      dockerfile: Dockerfile
    container_name: ocserv-agent-github-runner-debian
    hostname: github-runner-debian
    restart: unless-stopped

    environment:
      # Repository URL
      - REPO_URL=https://github.com/dantte-lp/ocserv-agent

      # Runner configuration
      - RUNNER_NAME=debian-runner-ocserv-agent
      - RUNNER_LABELS=self-hosted,linux,x64,debian,docker
      - RUNNER_GROUP=Default

      # Runner token (MUST be provided)
      # Get with: gh api --method POST /repos/dantte-lp/ocserv-agent/actions/runners/registration-token --jq '.token'
      - RUNNER_TOKEN=${RUNNER_TOKEN}

    volumes:
      # Mount project directory for builds
      - ../../:/workspace:rw

      # Mount Docker socket for Docker-in-Docker
      - /run/podman/podman.sock:/var/run/docker.sock

      # Note: _work directory uses container storage (no persistent volume needed)
      # GitHub Actions clones repos fresh for each job

    # Privileged mode for Docker-in-Docker
    privileged: true

    # Security options
    security_opt:
      - label=disable

    # Network
    networks:
      - runner-net-debian

networks:
  runner-net-debian:
    driver: bridge
