version: '3.8'

services:
  github-runner:
    build:
      context: github-runner
      dockerfile: Dockerfile
    container_name: ocserv-agent-github-runner
    hostname: github-runner
    restart: unless-stopped

    environment:
      # Repository URL
      - REPO_URL=https://github.com/dantte-lp/ocserv-agent

      # Runner configuration
      - RUNNER_NAME=oraclelinux-runner-ocserv-agent
      - RUNNER_LABELS=self-hosted,linux,x64,oracle-linux,rpm-build,mock,podman
      - RUNNER_GROUP=Default

      # Runner token (MUST be provided)
      # Get with: gh api --method POST /repos/dantte-lp/ocserv-agent/actions/runners/registration-token --jq '.token'
      - RUNNER_TOKEN=${RUNNER_TOKEN}

      # Podman configuration for rootful mode (required for container actions)
      - BUILDAH_ISOLATION=chroot
      - STORAGE_DRIVER=vfs

    volumes:
      # Mount project directory for builds
      - ../../:/workspace:rw

      # Mount Docker socket for Docker-in-Docker (if needed)
      # - /var/run/docker.sock:/var/run/docker.sock

      # Note: _work directory uses container storage (no persistent volume needed)
      # GitHub Actions clones repos fresh for each job

    # Privileged mode for podman-in-podman (required for container actions)
    privileged: true

    # Security options
    security_opt:
      - label=disable

    # Network
    networks:
      - runner-net

networks:
  runner-net:
    driver: bridge
